### ISSUE TITLE
About VS Code Vertical Tags.

### ISSUE THREAD

**Issue by 625781186** [orange4glace/vs-lib#1]
I'm sorry to leave a message here,
but I sent email or @you in the issue, 
but you didn't reply.

---

https://github.com/microsoft/vscode/issues/108264#issuecomment-715372778

![F~0UJSG M@UR{Y@BP}$B VW hc](https://user-images.githubusercontent.com/30521429/125179316-3458d580-e220-11eb-9874-79854b78037d.gif)

@orange4glace

Wow!! amazing !
Can you write an article to guide me and let me experience it ?

**Comment by orange4glace** [comment]
Hi @625781186 ! Sorry for the response! It can be done by directly editing the source code of the VSCode and unfortunately I don't have the code anymore.

**Comment by 625781186** [comment]
> Hi @625781186 ! Sorry for the response! It can be done by directly editing the source code of the VSCode and unfortunately I don't have the code anymore.

That's a shame.
